#!/bin/sh
set -e
gitdir="`git rev-parse --git-dir`"
trap 'rm -f "$gitdir/$$.tags"' EXIT
if [ "${PWD##$GOPATH}" != "$PWD" ]; then
  gotags -tag-relative -R -f "$gitdir/$$.tags" .
else
  git ls-files | \
    ctags --tag-relative -L - -f "$gitdir/$$.tags" --languages=-sql
fi
mv "$gitdir/$$.tags" "$gitdir/tags"

